spring:
  application:
    name: greeting-service
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

greeting-service:  
  greeting: "Hello - dev 3"
  default-value: "world"
  